### ISSUE TITLE
At least one reason option does not fit inside the button.

### ISSUE THREAD

**Issue by b34st80y** [b34st80y/oigo_app#4]
![image](https://user-images.githubusercontent.com/19982841/75058699-79ecf500-54a9-11ea-9319-390d0a0fa8cd.png)

**Comment by b34st80y** [comment]
supposed to say "about loving someone who doesnt love me"

**Comment by JamesWR1215** [comment]
I adjusted the height of the custom buttons, all options now fit within their boxes
